#!/bin/bash
# Generates every transcript in Chapter 25, "merge".
#
#   bash sandbox/scripts/ch25-merge.sh [dir]
#
# No `set -e`: many commands are shown failing on purpose.
#
# Git opens an editor for a merge message only when standard input and output
# are a terminal, which the sandbox never is. Every command that makes a merge
# commit without -m therefore says --no-edit, or sets GIT_EDITOR, so that the
# printed command behaves the same for a reader.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/../lib/sandbox.sh"

sb_root "${1:-$(mktemp -d)}" >/dev/null
exec </dev/null

# Run a command that makes a commit, then tick the clock like sb_commit.
m() { sb_run "$1"; sb_tick; }

# ---------------------------------------------------------------------------
# A garden planner.
git init -q --bare "$SANDBOX_ROOT/server.git"
sb_fresh "$SANDBOX_ROOT/garden" >/dev/null
git remote add origin "$SANDBOX_ROOT/server.git"
sb_write plants.txt "tomato" "basil" "mint"
sb_write README.md "# Garden planner"
sb_commit "Start the planner"
sb_write water.txt "tomato: daily" "basil: daily"
sb_commit "Add a watering plan"
git push -q -u origin main

# `lettuce`: main will stay an ancestor of its start (a fast-forward from main~1).
git switch -q -c lettuce
sb_write plants.txt "tomato" "basil" "mint" "lettuce"
sb_commit "Plant lettuce"
sb_write water.txt "tomato: daily" "basil: daily" "lettuce: daily"
sb_commit "Water the lettuce"

# `compost`: a separate file.
git switch -q -c compost main
sb_write compost.txt "kitchen scraps" "leaves"
sb_commit "Start composting"
sb_write compost.txt "kitchen scraps" "leaves" "no meat"
sb_commit "Add a compost rule"

# Two small branches for merging several at once.
git switch -q -c paths main
sb_write paths.txt "gravel path"
sb_commit "Lay a gravel path"
git switch -q -c pond main
sb_write pond.txt "small pond"
sb_commit "Dig a pond"

# `frost`: changes the first line of water.txt, as main will.
git switch -q -c frost main
sb_write water.txt "tomato: every other day" "basil: daily"
sb_commit "Water less in frost"

git switch -q main
sb_write README.md "# Garden planner" "Plans for a small garden."
sb_write water.txt "tomato: twice a day" "basil: daily"
sb_commit "Water tomatoes more"

# Someone else pushed to the server.
git clone -q "$SANDBOX_ROOT/server.git" "$SANDBOX_ROOT/other"
( cd "$SANDBOX_ROOT/other"
  sb_write tools.txt "spade" "rake"
  sb_commit "List the tools"
  git push -q origin main )
git fetch -q origin

# =============================================================================
sb_say "--- M1. history ---"
sb_run "git log --oneline --graph --all --decorate"

sb_say "--- M2. fast-forward ---"
sb_run "git switch -q -C try main~1"
sb_run "git merge lettuce"
sb_run "git log --oneline --graph -3"
sb_run "git switch -q -C try main~1"
m "git merge --no-ff --no-edit lettuce"
sb_run "git log --oneline --graph -4"
sb_run "git merge lettuce"
sb_run "git switch -q -C try main~1"
sb_run "git merge --ff-only lettuce"
sb_run "git switch -q -C try main"
sb_run "git merge --ff-only lettuce; echo \"exit \$?\""
sb_run "git switch -q -C try main~1"
m "git -c merge.ff=false merge --no-edit lettuce"
sb_run "git switch -q -C try main"
sb_run "git -c merge.ff=only merge --no-edit compost"
m "git -c merge.ff=only merge --ff --no-edit compost"
sb_run "git log --oneline --graph -4"

sb_say "--- M3. true merge ---"
sb_run "git switch -q -C try main"
m "git merge --no-edit compost"
sb_run "git log --oneline --graph -5"
sb_run "git cat-file -p HEAD"
sb_run "git rev-parse HEAD^1 HEAD^2"
sb_run "git show HEAD"
sb_run "cat .git/ORIG_HEAD"
sb_run "git rev-parse main"
sb_run "git merge compost"
sb_run "git branch --merged"

sb_say "--- M4. messages ---"
sb_run "git switch -q -C try main"
m "GIT_EDITOR=cat git merge --edit compost"
sb_run "git switch -q -C try main"
m "git merge -m 'Bring in composting' compost"
sb_run "git log -1 --format=%B"
sb_run "git switch -q -C try main"
m "git merge --log --no-edit compost"
sb_run "git log -1 --format=%B"
sb_run "git switch -q -C try main"
m "git merge --log=1 --no-edit compost"
sb_run "git log -1 --format=%B"
sb_run "git switch -q -C try main"
m "git -c merge.log=true merge --no-log --no-edit compost"
sb_run "git log -1 --format=%B"
sb_run "git switch -q -C try main"
m "GIT_EDITOR=cat git merge -e -m 'Bring in composting' compost"
sb_run "git switch -q -C try main"
m "GIT_EDITOR=\"sed -i '1s/.*/Merge the compost work/'\" git merge -e compost"
sb_run "git log -1 --format=%s"
sb_write "$SANDBOX_ROOT/merge-msg.txt" "Merge composting" "" "# a line starting with a hash"
sb_run "cat ../merge-msg.txt"
sb_run "git switch -q -C try main"
m "git merge -F ../merge-msg.txt compost"
sb_run "git log -1 --format=%B"
sb_run "git switch -q -C try main"
m "git merge -F ../merge-msg.txt --cleanup=strip compost"
sb_run "git log -1 --format=%B"
sb_run "git switch -q -C try main"
m "git merge --signoff --no-edit compost"
sb_run "git log -1 --format=%B"
sb_run "git switch -q -C try main"
m "git merge --into-name release --no-edit compost"
sb_run "git log -1 --format=%s"
sb_run "git switch -q -C try main"
m "git -c merge.suppressDest=try merge --no-edit compost"
sb_run "git log -1 --format=%s"
sb_run "git switch -q main"
m "git merge --no-edit compost"
sb_run "git log -1 --format=%s"
sb_run "git reset -q --hard ORIG_HEAD"

sb_say "--- M5. output ---"
sb_run "git switch -q -C try main"
m "git merge --no-edit compost"
sb_run "git switch -q -C try main"
m "git merge --no-edit -n compost"
sb_run "git switch -q -C try main"
m "git merge --no-edit --no-stat compost"
sb_run "git switch -q -C try main"
m "git merge --no-edit --stat compost"
sb_run "git switch -q -C try main"
m "git merge --no-edit --compact-summary compost"
sb_run "git switch -q -C try main"
m "git merge --no-edit --summary compost"
sb_run "git switch -q -C try main"
m "git -c merge.stat=compact merge --no-edit compost"
sb_run "git switch -q -C try main"
m "git -c merge.stat=false merge --no-edit compost"
sb_run "git switch -q -C try main"
m "git merge --no-edit -q compost"
sb_run "git switch -q -C try main"
m "git merge --no-edit -v compost"
sb_run "git switch -q -C try main"
m "GIT_PROGRESS_DELAY=0 git merge --no-edit --progress compost"

sb_say "--- M6. no-commit and squash ---"
sb_run "git switch -q -C try main"
sb_run "git merge --no-commit compost"
sb_run "git status"
sb_run "ls .git/MERGE_HEAD .git/MERGE_MSG"
m "git commit --no-edit"
sb_run "git log --oneline --graph -3"
sb_run "git switch -q -C try main"
sb_run "git merge --no-commit compost"
m "GIT_EDITOR=true git merge --continue"
sb_run "git log --oneline -1"
sb_run "git switch -q -C try main~1"
sb_run "git merge --no-commit lettuce"
sb_run "git log --oneline -1"
sb_run "git switch -q -C try main~1"
sb_run "git merge --no-commit --no-ff lettuce"
sb_run "git merge --abort"
sb_run "git log --oneline -1"
sb_run "git switch -q -C try main"
sb_run "git merge --squash compost"
sb_run "git status --short"
sb_run "ls .git/MERGE_HEAD; cat .git/SQUASH_MSG"
m "git commit -q -m 'Add composting'"
sb_run "git log --oneline --graph -3"
sb_run "git branch -d compost"
sb_run "git merge --squash --commit compost"
sb_run "git switch -q -C try main"
m "git merge --squash --no-squash --no-edit compost"
sb_run "git log --oneline --graph -3"
sb_run "git switch -q -C try main"
m "git merge --no-commit --commit --no-edit compost"
sb_run "git log --oneline -1"
sb_run "git switch -q -C try main~1"
sb_run "git merge --squash lettuce"
sb_run "git status --short"
sb_run "git log --oneline -1"
sb_run "git reset -q --hard"

sb_say "--- M7. several ---"
sb_run "git switch -q -C try main"
m "git merge --no-edit paths pond"
sb_run "git log --oneline --graph -5"
sb_run "git cat-file -p HEAD | head -4"
sb_run "git switch -q -C try main"
sb_run "git merge --no-edit paths frost"
sb_run "git status --short"
sb_run "ls .git/MERGE_HEAD"
sb_run "git merge --abort"
sb_run "git log --oneline -1"

sb_say "--- M8. stops ---"
sb_run "git switch -q -C try main"
sb_run "git merge frost"
sb_run "git status"
sb_run "ls .git/MERGE_HEAD"
sb_run "git merge compost"
sb_run "git commit -q -m 'Try to commit'"
sb_run "git merge --abort"
sb_run "git status --short"
sb_run "git merge frost"
sb_run "printf 'tomato: every other day\\nbasil: daily\\n' > water.txt"
sb_run "git merge --continue"
sb_run "git add water.txt"
m "GIT_EDITOR=cat git merge --continue"
sb_run "git log --oneline --graph -4"
sb_run "git switch -q -C try main"
sb_run "git merge frost"
sb_run "git merge --quit"
sb_run "git status --short"
sb_run "ls .git/MERGE_HEAD"
sb_run "git reset -q --hard"
sb_run "git merge --abort"
sb_run "git merge --continue"

sb_say "--- M9. local changes ---"
sb_run "git switch -q -C try main"
sb_write plants.txt "tomatoes" "basil" "mint"
sb_write compost.txt "my notes"
sb_run "git status --short"
sb_run "git merge --no-edit compost"
sb_run "rm compost.txt"
m "git merge --no-edit compost"
sb_run "git status --short"
sb_run "git switch -q -C try main"
sb_run "git merge --no-edit lettuce"
sb_run "git -c merge.autoStash=true merge --no-autostash --no-edit lettuce"
m "git merge --no-edit --autostash lettuce"
sb_run "git status --short"
sb_run "git stash list"
sb_run "git restore plants.txt"
sb_run "git switch -q -C try main"
sb_write plants.txt "tomato" "basil" "mint" "sage"
m "git merge --no-edit --autostash lettuce"
sb_run "git status --short"
sb_run "git stash list"
sb_run "git reset -q --hard"
sb_run "git stash drop"
sb_run "git switch -q -C try main"
sb_write README.md "# Garden planner" "Plans for a small garden." "Draft."
sb_run "git add README.md"
sb_run "git merge --no-edit compost"
sb_run "git restore --staged --worktree README.md"
sb_write plants.txt "tomatoes" "basil" "mint"
sb_run "git merge --autostash frost"
sb_run "git status --short"
sb_run "git stash list"
sb_run "git merge --abort"
sb_run "git status --short"
sb_run "git stash list"
sb_run "git merge --autostash frost"
sb_run "printf 'tomato: every other day\nbasil: daily\n' > water.txt"
sb_run "git add water.txt"
m "GIT_EDITOR=true git merge --continue"
sb_run "git status --short"
sb_run "git switch -q -C try main"
sb_run "git restore plants.txt"
sb_write pond.txt "my pond notes"
sb_run "git merge --no-edit pond"
sb_run "rm pond.txt"

sb_say "--- M10. what to merge ---"
sb_run "git switch -q main"
sb_run "git branch -vv --list main"
m "git merge --no-edit"
sb_run "git log --oneline --graph -4"
sb_run "git reset -q --hard ORIG_HEAD"
sb_run "git -c merge.defaultToUpstream=false merge"
sb_run "git switch -q -C try main"
sb_run "git merge"
m "git merge --no-edit origin/main"
sb_run "git log -1 --format=%s"
sb_run "git tag -a -m 'Spring planting' spring main"
sb_run "git switch -q -C try lettuce"
m "git merge --no-edit spring"
sb_run "git log -1 --format=%B"
sb_run "git switch -q -C try main~1"
sb_run "git merge --no-edit spring"
sb_run "git log --oneline -1"
sb_run "git merge nosuch"
sb_run "git merge HEAD"
sb_run "git merge main~2"
sb_run "git switch -q --detach main"
m "git merge --no-edit compost"
sb_run "git log --oneline --graph -3"
sb_run "git switch -q -C try main"
git switch -q --orphan wiki
sb_write wiki.txt "Gardening wiki"
sb_commit "Start a wiki"
git switch -q try
sb_run "git log --oneline wiki"
sb_run "git merge --no-edit wiki"
m "git merge --allow-unrelated-histories --no-edit wiki"
sb_run "git log --oneline --graph -5"
sb_run "ls"

sb_say "--- M11. undo ---"
sb_run "git switch -q -C try main"
m "git merge --no-edit compost"
sb_run "git reset --hard ORIG_HEAD"
m "git merge --no-edit compost"
m "git revert -m 1 --no-edit HEAD"
sb_run "git log --oneline --graph -4"
sb_run "ls"
sb_run "git merge --no-edit compost"

sb_say "--- M12. neighbours ---"
sb_run "git merge-base main compost"
sb_run "git merge-tree --write-tree main compost"
sb_run "git merge-tree --write-tree main frost; echo \"exit \$?\""
sb_run "git switch -q -C try main~1"
m "git -c branch.try.mergeOptions=--no-ff merge --no-edit lettuce"
sb_run "git log --oneline --graph -3"
