#!/bin/bash
# Generates every transcript in Chapter 26, "Conflicts".
#
#   bash sandbox/scripts/ch26-conflicts.sh [dir]
#
# No `set -e`: conflicts make many commands exit non-zero on purpose.
#
# As in ch25, every command that makes a merge commit says --no-edit or sets
# GIT_EDITOR, because Git opens an editor only on a terminal.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/../lib/sandbox.sh"

sb_root "${1:-$(mktemp -d)}" >/dev/null
exec </dev/null

m() { sb_run "$1"; sb_tick; }

# ---------------------------------------------------------------------------
# A cafe's menu, changed on two branches.
sb_fresh "$SANDBOX_ROOT/cafe" >/dev/null
sb_write menu.txt "Soup 4" "Salad 5" "Cake 3" "Pie 4" "Bun 2" "Tart 5" "Scone 2" "Muffin 3" "Cookie 1" "Juice 4"
sb_write specials.txt "Monday: pie"
sb_write notes.txt "Order flour on Fridays"
printf 'PNG\0logo v1\n' > logo.png
sb_commit "Open the cafe"

git switch -q -c prices
sb_write menu.txt "Soup 6" "Bread 2" "Salad 5" "Cake 3" "Pie 4" "Bun 2" "Tart 5" "Scone 2" "Muffin 3" "Cookie 1" "Juice 4"
sb_write specials.txt "Monday: pie" "Tuesday: soup of the day"
sb_write hours.txt "Mon-Fri 8-18"
sb_write drinks.txt "Tea 2" "Coffee 3"
printf 'PNG\0logo blue\n' > logo.png
sb_commit "Raise prices, add specials, hours and drinks"

git switch -q main
sb_write menu.txt "Soup 5" "Bread 2" "Salad 5" "Cake 3" "Pie 4" "Bun 2" "Tart 5" "Scone 2" "Muffin 3" "Cookie 1" "Juice 3"
git rm -q specials.txt
sb_write hours.txt "Mon-Sat 7-19"
printf 'PNG\0logo green\n' > logo.png
sb_commit "Update the menu, drop specials, add hours"

# Branches for other kinds of conflict.
git switch -q -c left main
git mv notes.txt notes.md
sb_commit "Rename notes to Markdown"
git switch -q -c right main
git mv notes.txt todo.txt
sb_commit "Rename notes to a to-do list"
git switch -q -c gone main
git rm -q notes.txt
sb_commit "Delete the notes"
git switch -q -c dir-side main
sb_write kitchen/stock.txt "flour"
sb_commit "Add a kitchen directory"
git switch -q -c file-side main
sb_write kitchen "the kitchen is closed"
sb_commit "Add a kitchen file"
git switch -q main

# =============================================================================
sb_say "--- C1. history ---"
sb_run "git log --oneline --graph --all --decorate"
sb_run "git diff main~1 prices --stat"
sb_run "git diff main~1 main --stat"

sb_say "--- C2. reading ---"
sb_run "git switch -q -C try main"
sb_run "git merge prices"
sb_run "git status"
sb_run "git status --short"
sb_run "cat menu.txt"
sb_run "cat hours.txt"
sb_run "cat specials.txt"
sb_run "cat -A logo.png"

sb_say "--- C3. styles ---"
sb_run "git restore --conflict=diff3 menu.txt"
sb_run "head -9 menu.txt"
sb_run "git checkout --conflict=zdiff3 menu.txt"
sb_run "head -7 menu.txt"
sb_run "git restore -m menu.txt"
sb_run "head -5 menu.txt"
sb_run "git merge --abort"
sb_run "git -c merge.conflictStyle=diff3 merge prices >/dev/null"
sb_run "head -9 menu.txt"
sb_run "git merge --abort"
sb_run "echo 'menu.txt conflict-marker-size=12' > .gitattributes"
sb_run "git merge prices >/dev/null"
sb_run "head -5 menu.txt"
sb_run "git merge --abort"
sb_run "rm .gitattributes"

sb_say "--- C4. stages ---"
sb_run "git merge prices >/dev/null"
sb_run "git ls-files -u"
sb_run "git ls-files --stage"
sb_run "git show :1:menu.txt | head -3"
sb_run "git show :2:menu.txt | head -3"
sb_run "git show :3:menu.txt | head -3"
sb_run "git show :1:hours.txt"
sb_run "git show :2:specials.txt"
sb_run "git show :3:specials.txt"
sb_run "git rev-parse MERGE_HEAD AUTO_MERGE"
sb_run "cat .git/MERGE_MSG"

sb_say "--- C5. diffs ---"
sb_run "git diff"
sb_run "git diff --cc menu.txt"
sb_run "git diff -c menu.txt"
sb_run "git diff --base menu.txt"
sb_run "git diff --ours menu.txt"
sb_run "git diff --theirs menu.txt"
sb_run "git diff -1 hours.txt"
sb_run "git diff -2 hours.txt"
sb_run "git diff -3 hours.txt"
sb_run "git diff -0"
sb_run "git diff --name-only --diff-filter=U"
sb_run "git diff --cached --name-status"
sb_run "git log --merge --oneline"
sb_run "git log --merge --oneline --left-right"
sb_run "git log --merge -p --format='%h %s' -- hours.txt"
sb_run "git diff HEAD -- hours.txt"
sb_run "git diff MERGE_HEAD -- hours.txt"

sb_say "--- C6. resolving ---"
sb_run "git restore menu.txt"
sb_run "printf 'Soup 5.5\\nBread 2\\n<<<<<<< HEAD\\n' > menu.txt"
sb_run "git diff AUTO_MERGE -- menu.txt"
sb_run "git diff --check"
sb_run "printf 'Soup 5.5\\nBread 2\\nSalad 5\\nCake 3\\nPie 4\\nBun 2\\nTart 5\\nScone 2\\nMuffin 3\\nCookie 1\\nJuice 3\\n' > menu.txt"
sb_run "git diff menu.txt"
sb_run "git add menu.txt"
sb_run "git status --short"
sb_run "git restore -m menu.txt"
sb_run "git status --short"
sb_run "head -5 menu.txt"
sb_run "printf 'Soup 5.5\\nBread 2\\nSalad 5\\nCake 3\\nPie 4\\nBun 2\\nTart 5\\nScone 2\\nMuffin 3\\nCookie 1\\nJuice 3\\n' > menu.txt"
sb_run "git add menu.txt"
sb_run "git diff --check"
sb_run "git add hours.txt"
sb_run "git status --short"
sb_run "git diff --check"
sb_run "git diff --cached --check"
sb_run "git restore --theirs hours.txt"
sb_run "git checkout --theirs hours.txt"
sb_run "head -1 hours.txt"
sb_run "git restore -m hours.txt"
sb_run "git restore --theirs hours.txt"
sb_run "cat hours.txt"
sb_run "git checkout --ours hours.txt"
sb_run "cat hours.txt"
sb_run "git add hours.txt"
sb_run "git checkout --theirs logo.png"
sb_run "git add logo.png"
sb_run "git rm specials.txt"
sb_run "git status"
m "GIT_EDITOR=cat git merge --continue"
sb_run "git show"
sb_run "git log -1 --cc --format=%s"
sb_run "git log -1 -c --format=%s -- menu.txt"
sb_run "git log -1 --format=%s --stat --diff-merges=first-parent"
sb_run "git show --remerge-diff --format=%s"

sb_say "--- C7. restore and checkout on conflicts ---"
sb_run "git switch -q -C try main"
sb_run "git merge prices >/dev/null"
sb_run "git restore hours.txt"
sb_run "git checkout -- hours.txt"
sb_run "git checkout -f -- hours.txt"
sb_run "git status --short"
sb_run "git checkout --theirs ."
sb_run "git status --short"
sb_run "cat hours.txt"
sb_run "git checkout --ours specials.txt"
sb_run "ls specials.txt"
sb_run "git restore --ours -- '*.txt'"
sb_run "cat hours.txt"
sb_run "ls specials.txt"
sb_run "git merge --abort"
sb_run "git switch -q -C try prices"
sb_run "git rebase main"
sb_run "head -5 menu.txt"
sb_run "git checkout --ours menu.txt"
sb_run "head -1 menu.txt"
sb_run "git checkout --theirs menu.txt"
sb_run "head -1 menu.txt"
sb_run "git rebase --abort"

sb_say "--- C8. other kinds ---"
sb_run "git switch -q -C try left"
sb_run "git merge right"
sb_run "git status --short"
sb_run "git ls-files -u"
sb_run "git rm notes.txt notes.md"
sb_run "git add todo.txt"
sb_run "git status --short"
sb_run "git merge --abort"
sb_run "git switch -q -C try left"
sb_run "git merge gone"
sb_run "git status --short"
sb_run "git rm notes.md"
sb_run "git status --short"
sb_run "git merge --abort"
sb_run "git switch -q -C try gone"
sb_run "git merge left"
sb_run "git status --short"
sb_run "git add notes.md"
sb_run "git status --short"
sb_run "git merge --abort"
sb_run "git switch -q -C try dir-side"
sb_run "git merge file-side"
sb_run "git status --short"
sb_run "ls"
sb_run "git mv kitchen~file-side kitchen.txt"
sb_run "mv kitchen~file-side kitchen.txt"
sb_run "git add kitchen.txt kitchen~file-side"
sb_run "git status --short"
sb_run "git merge --abort"

sb_say "--- C9. other commands ---"
sb_run "git switch -q -C try main"
sb_run "git cherry-pick prices >/dev/null"
sb_run "head -5 menu.txt"
sb_run "git log --merge --oneline --left-right"
sb_run "git cherry-pick --abort"
sb_run "git switch -q -C try main~1"
sb_write menu.txt "Soup 7" "Salad 5" "Cake 3" "Pie 4" "Bun 2" "Tart 5" "Scone 2" "Muffin 3" "Cookie 1" "Juice 4"
sb_run "git stash -q"
sb_run "git merge -q --ff-only prices"
sb_run "git stash pop"
sb_run "head -5 menu.txt"
sb_run "git reset -q --hard"
sb_run "git stash drop"

sb_say "--- C10. mergetool ---"
sb_run "git switch -q -C try main"
sb_run "git merge prices >/dev/null"
sb_run "git mergetool --tool-help | sed -n '1,4p'"
sb_run "git config set mergetool.take-theirs.cmd 'cp \"\$REMOTE\" \"\$MERGED\"'"
sb_run "git config set mergetool.take-theirs.trustExitCode true"
sb_run "git mergetool --tool=take-theirs menu.txt"
sb_run "git status --short"
sb_run "head -1 menu.txt"
sb_run "printf 'd\\n' | git mergetool --tool=take-theirs specials.txt; echo"
sb_run "git status --short"
sb_run "printf '\\n' | git mergetool --prompt --tool=take-theirs hours.txt; echo"
sb_run "git status --short"
sb_run "git -c merge.guitool=take-theirs mergetool -g logo.png"
sb_run "git status --short"
sb_run "git merge --abort"
sb_run "rm *.orig"
sb_run "git merge prices >/dev/null"
sb_run "git -c merge.tool=take-theirs -c merge.guitool=nosuch mergetool --gui --no-gui logo.png"
sb_run "printf 'm\\n' | git mergetool -t take-theirs specials.txt; echo"
sb_run "git status --short"
sb_run "git merge --abort"
sb_run "rm *.orig"
sb_run "git merge prices >/dev/null"
sb_run "printf 'menu.txt\\nhours.txt\\n' > order"
sb_run "printf 'd\\n' | git -c mergetool.prompt=true -c mergetool.keepBackup=false mergetool -y -Oorder --tool=take-theirs; echo"
sb_run "git status --short"
sb_run "git merge --abort"
sb_run "rm order"

sb_say "--- C11. rerere ---"
sb_run "git config set rerere.enabled true"
sb_run "git switch -q -C try main"
sb_run "git merge prices"
sb_run "git rerere status"
sb_run "printf 'Soup 5.5\\nBread 2\\nSalad 5\\nCake 3\\nPie 4\\nBun 2\\nTart 5\\nScone 2\\nMuffin 3\\nCookie 1\\nJuice 3\\n' > menu.txt"
sb_run "git rerere diff"
sb_run "git rerere remaining"
sb_run "printf 'Mon-Fri 8-18\\nSat 7-19\\n' > hours.txt"
sb_run "git add menu.txt hours.txt logo.png"
sb_run "git rm -q specials.txt"
m "git commit --no-edit"
sb_run "ls .git/rr-cache"
sb_run "git switch -q -C try main"
sb_run "git merge prices"
sb_run "cat hours.txt"
sb_run "git status --short"
sb_run "git rerere remaining"
sb_run "git merge --abort"
sb_run "git switch -q -C try prices"
sb_run "git merge main >/dev/null"
sb_run "cat hours.txt"
sb_run "git merge --abort"
sb_run "git switch -q -C try main"
sb_run "git merge --rerere-autoupdate prices >/dev/null"
sb_run "git status --short"
sb_run "git merge --abort"
sb_run "git -c rerere.autoUpdate=true merge prices >/dev/null"
sb_run "git status --short"
sb_run "git merge --abort"
sb_run "git -c rerere.autoUpdate=true merge --no-rerere-autoupdate prices >/dev/null"
sb_run "git status --short"
sb_run "git rerere forget menu.txt"
sb_run "head -5 menu.txt"
sb_run "git rerere clear"
sb_run "git merge --abort"
sb_run "git rerere gc"
sb_run "git config unset rerere.enabled"
sb_run "git merge prices >/dev/null"
sb_run "printf 'd\\n' | git mergetool --tool=take-theirs; echo"
sb_run "git status --short"
sb_run "git merge --abort"
sb_run "rm *.orig"
sb_run "git config set rerere.enabled false"
sb_run "git merge prices >/dev/null"
sb_run "git merge --abort"

sb_say "--- C12. merge-file ---"
mkdir -p "$SANDBOX_ROOT/files"
cd "$SANDBOX_ROOT/files"
sb_write base.txt "Soup 4" "Salad 5"
sb_write ours.txt "Soup 5" "Bread 2" "Salad 5"
sb_write theirs.txt "Soup 6" "Bread 2" "Salad 5"
sb_run "cd ../files"
sb_run "git merge-file -p ours.txt base.txt theirs.txt; echo \"exit \$?\""
sb_run "git merge-file -p --diff3 ours.txt base.txt theirs.txt"
sb_run "git merge-file -p --zdiff3 ours.txt base.txt theirs.txt"
sb_run "git -c merge.conflictStyle=diff3 merge-file -p ours.txt base.txt theirs.txt"
sb_run "git merge-file -p --ours ours.txt base.txt theirs.txt; echo \"exit \$?\""
sb_run "git merge-file -p --theirs ours.txt base.txt theirs.txt"
sb_run "git merge-file -p --union ours.txt base.txt theirs.txt"
sb_run "git merge-file -p -L mine -L original -L yours ours.txt base.txt theirs.txt"
sb_run "git merge-file -p --marker-size=3 ours.txt base.txt theirs.txt"
sb_run "cp ours.txt result.txt"
sb_run "git merge-file result.txt base.txt theirs.txt; echo \"exit \$?\""
sb_run "cat result.txt"
sb_run "diff3 -m ours.txt base.txt theirs.txt"

# Two changes three lines apart, and two changes eight lines apart.
sb_write near-base.txt "Soup 4" "Salad 5" "Cake 3" "Pie 4" "Bun 2"
sb_write near-ours.txt "Soup 5" "Salad 5" "Cake 3" "Pie 4" "Bun 3"
sb_write near-theirs.txt "Soup 6" "Salad 5" "Cake 3" "Pie 4" "Bun 4"
sb_write far-base.txt "Soup 4" "Salad 5" "Cake 3" "Pie 4" "Bun 2" "Tart 5" "Scone 2" "Muffin 3" "Cookie 1" "Juice 4"
sb_write far-ours.txt "Soup 5" "Salad 5" "Cake 3" "Pie 4" "Bun 2" "Tart 5" "Scone 2" "Muffin 3" "Cookie 1" "Juice 3"
sb_write far-theirs.txt "Soup 6" "Salad 5" "Cake 3" "Pie 4" "Bun 2" "Tart 5" "Scone 2" "Muffin 3" "Cookie 1" "Juice 5"
sb_run "git merge-file -p near-ours.txt near-base.txt near-theirs.txt; echo \"exit \$?\""
sb_run "git merge-file -p far-ours.txt far-base.txt far-theirs.txt >/dev/null; echo \"exit \$?\""

printf 'PNG\0logo v1\n' > base.png
printf 'PNG\0logo green\n' > ours.png
printf 'PNG\0logo blue\n' > theirs.png
sb_run "git merge-file ours.png base.png theirs.png; echo \"exit \$?\""
sb_run "git merge-file -q ours.png base.png theirs.png; echo \"exit \$?\""

sb_run "cd ../cafe"
cd "$SANDBOX_ROOT/cafe"
sb_run "git merge-file -p --object-id main:menu.txt main~1:menu.txt prices:menu.txt | head -5"
sb_run "git -c merge.conflictStyle=diff3 merge-file -p --object-id main:menu.txt main~1:menu.txt prices:menu.txt | head -9"
sb_run "git merge-file --object-id main:menu.txt main~1:menu.txt prices:menu.txt"
blob=$(git merge-file --object-id main:menu.txt main~1:menu.txt prices:menu.txt)
sb_run "git cat-file -p ${blob:0:7} | head -5"
